export interface TemplateItem {
  id: number;
  name: string;
  category: string;
  baseStyle: "modern" | "classic" | "tech" | "creative" | "executive" | "academic" | "chic" | "midnight" | "metro" | "editorial" | "outline" | "brutalist" | "slate" | "healthcare" | "future" | "profile-photo";
  colorAccent: string;
  badge?: string;
  description: string;
}

export const TEMPLATE_CATEGORIES = [
  "All Templates",
  "Modern Professional",
  "Minimalist",
  "Creative & Designer",
  "Technology & Software",
  "Student & Fresher",
  "Executive & Leadership",
  "ATS-Friendly",
  "Futuristic / AI / Digital",
  "Neomorphism / Liquid Glass",
  "Industry-Specific"
] as const;

export type TemplateCategory = typeof TEMPLATE_CATEGORIES[number];

const categoryStyleMap: Record<string, { baseStyle: TemplateItem["baseStyle"]; defaultAccent: string }> = {
  "Modern Professional": { baseStyle: "modern", defaultAccent: "#d97706" },
  "Minimalist": { baseStyle: "chic", defaultAccent: "#374151" },
  "Creative & Designer": { baseStyle: "creative", defaultAccent: "#ec4899" },
  "Technology & Software": { baseStyle: "tech", defaultAccent: "#0284c7" },
  "Student & Fresher": { baseStyle: "outline", defaultAccent: "#059669" },
  "Executive & Leadership": { baseStyle: "executive", defaultAccent: "#1d4ed8" },
  "ATS-Friendly": { baseStyle: "classic", defaultAccent: "#1e293b" },
  "Futuristic / AI / Digital": { baseStyle: "future", defaultAccent: "#9333ea" },
  "Neomorphism / Liquid Glass": { baseStyle: "midnight", defaultAccent: "#f59e0b" },
  "Industry-Specific": { baseStyle: "metro", defaultAccent: "#4f46e5" }
};

const templateRawData: { id: number; name: string; category: string }[] = [
  // 1. Modern Professional (1–100)
  { id: 1, name: "Modern Edge", category: "Modern Professional" },
  { id: 2, name: "Executive Flow", category: "Modern Professional" },
  { id: 3, name: "Career Pro", category: "Modern Professional" },
  { id: 4, name: "Professional Grid", category: "Modern Professional" },
  { id: 5, name: "Clean Executive", category: "Modern Professional" },
  { id: 6, name: "Prime Resume", category: "Modern Professional" },
  { id: 7, name: "Career Canvas", category: "Modern Professional" },
  { id: 8, name: "Elite Profile", category: "Modern Professional" },
  { id: 9, name: "Modern Executive", category: "Modern Professional" },
  { id: 10, name: "Career Matrix", category: "Modern Professional" },
  { id: 11, name: "ProLine", category: "Modern Professional" },
  { id: 12, name: "WorkFlow", category: "Modern Professional" },
  { id: 13, name: "Career Frame", category: "Modern Professional" },
  { id: 14, name: "Professional One", category: "Modern Professional" },
  { id: 15, name: "Executive Plus", category: "Modern Professional" },
  { id: 16, name: "Career Vista", category: "Modern Professional" },
  { id: 17, name: "Prime Profile", category: "Modern Professional" },
  { id: 18, name: "ProCareer", category: "Modern Professional" },
  { id: 19, name: "Executive Grid", category: "Modern Professional" },
  { id: 20, name: "Career Focus", category: "Modern Professional" },
  { id: 21, name: "Modern Path", category: "Modern Professional" },
  { id: 22, name: "Career Bridge", category: "Modern Professional" },
  { id: 23, name: "ProFrame", category: "Modern Professional" },
  { id: 24, name: "Career Core", category: "Modern Professional" },
  { id: 25, name: "Executive Focus", category: "Modern Professional" },
  { id: 26, name: "Career Rise", category: "Modern Professional" },
  { id: 27, name: "Professional Arc", category: "Modern Professional" },
  { id: 28, name: "Career Sphere", category: "Modern Professional" },
  { id: 29, name: "Career Pulse", category: "Modern Professional" },
  { id: 30, name: "ProVista", category: "Modern Professional" },
  { id: 31, name: "Career Vision", category: "Modern Professional" },
  { id: 32, name: "Executive Path", category: "Modern Professional" },
  { id: 33, name: "Career Prime", category: "Modern Professional" },
  { id: 34, name: "WorkSphere", category: "Modern Professional" },
  { id: 35, name: "Career Axis", category: "Modern Professional" },
  { id: 36, name: "Professional Axis", category: "Modern Professional" },
  { id: 37, name: "Career Line", category: "Modern Professional" },
  { id: 38, name: "Executive Line", category: "Modern Professional" },
  { id: 39, name: "Career Point", category: "Modern Professional" },
  { id: 40, name: "ProPoint", category: "Modern Professional" },
  { id: 41, name: "Career Stack", category: "Modern Professional" },
  { id: 42, name: "Executive Stack", category: "Modern Professional" },
  { id: 43, name: "Career Structure", category: "Modern Professional" },
  { id: 44, name: "ProStructure", category: "Modern Professional" },
  { id: 45, name: "Career Blueprint", category: "Modern Professional" },
  { id: 46, name: "Professional Blueprint", category: "Modern Professional" },
  { id: 47, name: "Career Nexus", category: "Modern Professional" },
  { id: 48, name: "ProNexus", category: "Modern Professional" },
  { id: 49, name: "Career Horizon", category: "Modern Professional" },
  { id: 50, name: "Executive Horizon", category: "Modern Professional" },
  { id: 51, name: "Career Summit", category: "Modern Professional" },
  { id: 52, name: "Professional Summit", category: "Modern Professional" },
  { id: 53, name: "Career Peak", category: "Modern Professional" },
  { id: 54, name: "ProPeak", category: "Modern Professional" },
  { id: 55, name: "Career Elevate", category: "Modern Professional" },
  { id: 56, name: "Executive Elevate", category: "Modern Professional" },
  { id: 57, name: "Career Motion", category: "Modern Professional" },
  { id: 58, name: "Professional Motion", category: "Modern Professional" },
  { id: 59, name: "Career Stream", category: "Modern Professional" },
  { id: 60, name: "ProStream", category: "Modern Professional" },
  { id: 61, name: "Career Orbit", category: "Modern Professional" },
  { id: 62, name: "Executive Orbit", category: "Modern Professional" },
  { id: 63, name: "Career Sphere", category: "Modern Professional" },
  { id: 64, name: "Professional Sphere", category: "Modern Professional" },
  { id: 65, name: "Career Core", category: "Modern Professional" },
  { id: 66, name: "ProCore", category: "Modern Professional" },
  { id: 67, name: "Career Link", category: "Modern Professional" },
  { id: 68, name: "Executive Link", category: "Modern Professional" },
  { id: 69, name: "Career Network", category: "Modern Professional" },
  { id: 70, name: "Professional Network", category: "Modern Professional" },
  { id: 71, name: "Career Route", category: "Modern Professional" },
  { id: 72, name: "ProRoute", category: "Modern Professional" },
  { id: 73, name: "Career Journey", category: "Modern Professional" },
  { id: 74, name: "Executive Journey", category: "Modern Professional" },
  { id: 75, name: "Career Track", category: "Modern Professional" },
  { id: 76, name: "Professional Track", category: "Modern Professional" },
  { id: 77, name: "Career Trail", category: "Modern Professional" },
  { id: 78, name: "ProTrail", category: "Modern Professional" },
  { id: 79, name: "Career Gateway", category: "Modern Professional" },
  { id: 80, name: "Executive Gateway", category: "Modern Professional" },
  { id: 81, name: "Career Portal", category: "Modern Professional" },
  { id: 82, name: "Professional Portal", category: "Modern Professional" },
  { id: 83, name: "Career Launch", category: "Modern Professional" },
  { id: 84, name: "ProLaunch", category: "Modern Professional" },
  { id: 85, name: "Career Drive", category: "Modern Professional" },
  { id: 86, name: "Executive Drive", category: "Modern Professional" },
  { id: 87, name: "Career Impact", category: "Modern Professional" },
  { id: 88, name: "Professional Impact", category: "Modern Professional" },
  { id: 89, name: "Career Force", category: "Modern Professional" },
  { id: 90, name: "ProForce", category: "Modern Professional" },
  { id: 91, name: "Career Spark", category: "Modern Professional" },
  { id: 92, name: "Executive Spark", category: "Modern Professional" },
  { id: 93, name: "Career Rise", category: "Modern Professional" },
  { id: 94, name: "Professional Rise", category: "Modern Professional" },
  { id: 95, name: "Career Advance", category: "Modern Professional" },
  { id: 96, name: "ProAdvance", category: "Modern Professional" },
  { id: 97, name: "Career Momentum", category: "Modern Professional" },
  { id: 98, name: "Executive Momentum", category: "Modern Professional" },
  { id: 99, name: "Career Master", category: "Modern Professional" },
  { id: 100, name: "Professional Master", category: "Modern Professional" },

  // 2. Minimalist (101–200)
  { id: 101, name: "Minimal One", category: "Minimalist" },
  { id: 102, name: "Minimal Flow", category: "Minimalist" },
  { id: 103, name: "Minimal Grid", category: "Minimalist" },
  { id: 104, name: "Minimal Edge", category: "Minimalist" },
  { id: 105, name: "Minimalist Pro", category: "Minimalist" },
  { id: 106, name: "Pure Profile", category: "Minimalist" },
  { id: 107, name: "Simple Career", category: "Minimalist" },
  { id: 108, name: "Clean Canvas", category: "Minimalist" },
  { id: 109, name: "White Space", category: "Minimalist" },
  { id: 110, name: "ClearPath", category: "Minimalist" },
  { id: 111, name: "Mono Profile", category: "Minimalist" },
  { id: 112, name: "Pure Resume", category: "Minimalist" },
  { id: 113, name: "Simple Edge", category: "Minimalist" },
  { id: 114, name: "CleanLine", category: "Minimalist" },
  { id: 115, name: "Quiet Profile", category: "Minimalist" },
  { id: 116, name: "Minimal Frame", category: "Minimalist" },
  { id: 117, name: "PureLine", category: "Minimalist" },
  { id: 118, name: "Simple Matrix", category: "Minimalist" },
  { id: 119, name: "Clean Matrix", category: "Minimalist" },
  { id: 120, name: "Minimal Core", category: "Minimalist" },
  { id: 121, name: "White Edge", category: "Minimalist" },
  { id: 122, name: "Clear Resume", category: "Minimalist" },
  { id: 123, name: "Simple Structure", category: "Minimalist" },
  { id: 124, name: "Minimal Structure", category: "Minimalist" },
  { id: 125, name: "Pure Structure", category: "Minimalist" },
  { id: 126, name: "Clean Structure", category: "Minimalist" },
  { id: 127, name: "Minimal Axis", category: "Minimalist" },
  { id: 128, name: "Simple Axis", category: "Minimalist" },
  { id: 129, name: "Pure Axis", category: "Minimalist" },
  { id: 130, name: "Clean Axis", category: "Minimalist" },
  { id: 131, name: "Minimal Point", category: "Minimalist" },
  { id: 132, name: "Simple Point", category: "Minimalist" },
  { id: 133, name: "Pure Point", category: "Minimalist" },
  { id: 134, name: "Clean Point", category: "Minimalist" },
  { id: 135, name: "Minimal Focus", category: "Minimalist" },
  { id: 136, name: "Simple Focus", category: "Minimalist" },
  { id: 137, name: "Pure Focus", category: "Minimalist" },
  { id: 138, name: "Clean Focus", category: "Minimalist" },
  { id: 139, name: "Minimal Profile", category: "Minimalist" },
  { id: 140, name: "Simple Profile", category: "Minimalist" },
  { id: 141, name: "Pure Profile", category: "Minimalist" },
  { id: 142, name: "Clean Profile", category: "Minimalist" },
  { id: 143, name: "Minimal Career", category: "Minimalist" },
  { id: 144, name: "Simple Career Pro", category: "Minimalist" },
  { id: 145, name: "Pure Career", category: "Minimalist" },
  { id: 146, name: "Clean Career", category: "Minimalist" },
  { id: 147, name: "Minimal Executive", category: "Minimalist" },
  { id: 148, name: "Simple Executive", category: "Minimalist" },
  { id: 149, name: "Pure Executive", category: "Minimalist" },
  { id: 150, name: "Clean Executive", category: "Minimalist" },
  { id: 151, name: "Minimal Portfolio", category: "Minimalist" },
  { id: 152, name: "Simple Portfolio", category: "Minimalist" },
  { id: 153, name: "Pure Portfolio", category: "Minimalist" },
  { id: 154, name: "Clean Portfolio", category: "Minimalist" },
  { id: 155, name: "Minimal Professional", category: "Minimalist" },
  { id: 156, name: "Simple Professional", category: "Minimalist" },
  { id: 157, name: "Pure Professional", category: "Minimalist" },
  { id: 158, name: "Clean Professional", category: "Minimalist" },
  { id: 159, name: "Minimal Resume Pro", category: "Minimalist" },
  { id: 160, name: "Simple Resume Pro", category: "Minimalist" },
  { id: 161, name: "Pure Resume Pro", category: "Minimalist" },
  { id: 162, name: "Clean Resume Pro", category: "Minimalist" },
  { id: 163, name: "Minimal Modern", category: "Minimalist" },
  { id: 164, name: "Simple Modern", category: "Minimalist" },
  { id: 165, name: "Pure Modern", category: "Minimalist" },
  { id: 166, name: "Clean Modern", category: "Minimalist" },
  { id: 167, name: "Minimal Classic", category: "Minimalist" },
  { id: 168, name: "Simple Classic", category: "Minimalist" },
  { id: 169, name: "Pure Classic", category: "Minimalist" },
  { id: 170, name: "Clean Classic", category: "Minimalist" },
  { id: 171, name: "Minimal Vision", category: "Minimalist" },
  { id: 172, name: "Simple Vision", category: "Minimalist" },
  { id: 173, name: "Pure Vision", category: "Minimalist" },
  { id: 174, name: "Clean Vision", category: "Minimalist" },
  { id: 175, name: "Minimal Horizon", category: "Minimalist" },
  { id: 176, name: "Simple Horizon", category: "Minimalist" },
  { id: 177, name: "Pure Horizon", category: "Minimalist" },
  { id: 178, name: "Clean Horizon", category: "Minimalist" },
  { id: 179, name: "Minimal Focus Pro", category: "Minimalist" },
  { id: 180, name: "Simple Focus Pro", category: "Minimalist" },
  { id: 181, name: "Pure Focus Pro", category: "Minimalist" },
  { id: 182, name: "Clean Focus Pro", category: "Minimalist" },
  { id: 183, name: "Minimal Career Plus", category: "Minimalist" },
  { id: 184, name: "Simple Career Plus", category: "Minimalist" },
  { id: 185, name: "Pure Career Plus", category: "Minimalist" },
  { id: 186, name: "Clean Career Plus", category: "Minimalist" },
  { id: 187, name: "Minimal Elite", category: "Minimalist" },
  { id: 188, name: "Simple Elite", category: "Minimalist" },
  { id: 189, name: "Pure Elite", category: "Minimalist" },
  { id: 190, name: "Clean Elite", category: "Minimalist" },
  { id: 191, name: "Minimal Prime", category: "Minimalist" },
  { id: 192, name: "Simple Prime", category: "Minimalist" },
  { id: 193, name: "Pure Prime", category: "Minimalist" },
  { id: 194, name: "Clean Prime", category: "Minimalist" },
  { id: 195, name: "Minimal Signature", category: "Minimalist" },
  { id: 196, name: "Simple Signature", category: "Minimalist" },
  { id: 197, name: "Pure Signature", category: "Minimalist" },
  { id: 198, name: "Clean Signature", category: "Minimalist" },
  { id: 199, name: "Minimal Signature Pro", category: "Minimalist" },
  { id: 200, name: "Pure Signature Pro", category: "Minimalist" },

  // 3. Creative & Designer (201–300)
  { id: 201, name: "Creative Canvas", category: "Creative & Designer" },
  { id: 202, name: "Design Pulse", category: "Creative & Designer" },
  { id: 203, name: "Visual Story", category: "Creative & Designer" },
  { id: 204, name: "ArtBoard", category: "Creative & Designer" },
  { id: 205, name: "Creative Flow", category: "Creative & Designer" },
  { id: 206, name: "Design Grid", category: "Creative & Designer" },
  { id: 207, name: "Pixel Profile", category: "Creative & Designer" },
  { id: 208, name: "Visual Edge", category: "Creative & Designer" },
  { id: 209, name: "Creative Matrix", category: "Creative & Designer" },
  { id: 210, name: "Design Sphere", category: "Creative & Designer" },
  { id: 211, name: "ArtLine", category: "Creative & Designer" },
  { id: 212, name: "DesignWave", category: "Creative & Designer" },
  { id: 213, name: "Creative Orbit", category: "Creative & Designer" },
  { id: 214, name: "Visual Orbit", category: "Creative & Designer" },
  { id: 215, name: "Design Horizon", category: "Creative & Designer" },
  { id: 216, name: "Creative Horizon", category: "Creative & Designer" },
  { id: 217, name: "PixelPath", category: "Creative & Designer" },
  { id: 218, name: "ArtPath", category: "Creative & Designer" },
  { id: 219, name: "Design Journey", category: "Creative & Designer" },
  { id: 220, name: "Creative Journey", category: "Creative & Designer" },
  { id: 221, name: "Visual Journey", category: "Creative & Designer" },
  { id: 222, name: "DesignCraft", category: "Creative & Designer" },
  { id: 223, name: "CreativeCraft", category: "Creative & Designer" },
  { id: 224, name: "ArtCraft", category: "Creative & Designer" },
  { id: 225, name: "PixelCraft", category: "Creative & Designer" },
  { id: 226, name: "DesignLab", category: "Creative & Designer" },
  { id: 227, name: "CreativeLab", category: "Creative & Designer" },
  { id: 228, name: "VisualLab", category: "Creative & Designer" },
  { id: 229, name: "ArtLab", category: "Creative & Designer" },
  { id: 230, name: "Design Studio", category: "Creative & Designer" },
  { id: 231, name: "Creative Studio", category: "Creative & Designer" },
  { id: 232, name: "Visual Studio", category: "Creative & Designer" },
  { id: 233, name: "Art Studio", category: "Creative & Designer" },
  { id: 234, name: "Design Blueprint", category: "Creative & Designer" },
  { id: 235, name: "Creative Blueprint", category: "Creative & Designer" },
  { id: 236, name: "Visual Blueprint", category: "Creative & Designer" },
  { id: 237, name: "Art Blueprint", category: "Creative & Designer" },
  { id: 238, name: "Design Mosaic", category: "Creative & Designer" },
  { id: 239, name: "Creative Mosaic", category: "Creative & Designer" },
  { id: 240, name: "Visual Mosaic", category: "Creative & Designer" },
  { id: 241, name: "Art Mosaic", category: "Creative & Designer" },
  { id: 242, name: "Design Spectrum", category: "Creative & Designer" },
  { id: 243, name: "Creative Spectrum", category: "Creative & Designer" },
  { id: 244, name: "Visual Spectrum", category: "Creative & Designer" },
  { id: 245, name: "Art Spectrum", category: "Creative & Designer" },
  { id: 246, name: "Design Bloom", category: "Creative & Designer" },
  { id: 247, name: "Creative Bloom", category: "Creative & Designer" },
  { id: 248, name: "Visual Bloom", category: "Creative & Designer" },
  { id: 249, name: "Art Bloom", category: "Creative & Designer" },
  { id: 250, name: "Design Spark", category: "Creative & Designer" },
  { id: 251, name: "Creative Spark", category: "Creative & Designer" },
  { id: 252, name: "Visual Spark", category: "Creative & Designer" },
  { id: 253, name: "Art Spark", category: "Creative & Designer" },
  { id: 254, name: "Design Motion", category: "Creative & Designer" },
  { id: 255, name: "Creative Motion", category: "Creative & Designer" },
  { id: 256, name: "Visual Motion", category: "Creative & Designer" },
  { id: 257, name: "Art Motion", category: "Creative & Designer" },
  { id: 258, name: "Design Flow Pro", category: "Creative & Designer" },
  { id: 259, name: "Creative Flow Pro", category: "Creative & Designer" },
  { id: 260, name: "Visual Flow Pro", category: "Creative & Designer" },
  { id: 261, name: "Art Flow Pro", category: "Creative & Designer" },
  { id: 262, name: "Design Fusion", category: "Creative & Designer" },
  { id: 263, name: "Creative Fusion", category: "Creative & Designer" },
  { id: 264, name: "Visual Fusion", category: "Creative & Designer" },
  { id: 265, name: "Art Fusion", category: "Creative & Designer" },
  { id: 266, name: "Design Frame", category: "Creative & Designer" },
  { id: 267, name: "Creative Frame", category: "Creative & Designer" },
  { id: 268, name: "Visual Frame", category: "Creative & Designer" },
  { id: 269, name: "Art Frame", category: "Creative & Designer" },
  { id: 270, name: "Design Focus", category: "Creative & Designer" },
  { id: 271, name: "Creative Focus", category: "Creative & Designer" },
  { id: 272, name: "Visual Focus", category: "Creative & Designer" },
  { id: 273, name: "Art Focus", category: "Creative & Designer" },
  { id: 274, name: "Design Perspective", category: "Creative & Designer" },
  { id: 275, name: "Creative Perspective", category: "Creative & Designer" },
  { id: 276, name: "Visual Perspective", category: "Creative & Designer" },
  { id: 277, name: "Art Perspective", category: "Creative & Designer" },
  { id: 278, name: "Design Identity", category: "Creative & Designer" },
  { id: 279, name: "Creative Identity", category: "Creative & Designer" },
  { id: 280, name: "Visual Identity", category: "Creative & Designer" },
  { id: 281, name: "Art Identity", category: "Creative & Designer" },
  { id: 282, name: "Design Signature", category: "Creative & Designer" },
  { id: 283, name: "Creative Signature", category: "Creative & Designer" },
  { id: 284, name: "Visual Signature", category: "Creative & Designer" },
  { id: 285, name: "Art Signature", category: "Creative & Designer" },
  { id: 286, name: "Design Story", category: "Creative & Designer" },
  { id: 287, name: "Creative Story", category: "Creative & Designer" },
  { id: 288, name: "Visual Story Pro", category: "Creative & Designer" },
  { id: 289, name: "Art Story", category: "Creative & Designer" },
  { id: 290, name: "Design Vision", category: "Creative & Designer" },
  { id: 291, name: "Creative Vision", category: "Creative & Designer" },
  { id: 292, name: "Visual Vision", category: "Creative & Designer" },
  { id: 293, name: "Art Vision", category: "Creative & Designer" },
  { id: 294, name: "Design Expression", category: "Creative & Designer" },
  { id: 295, name: "Creative Expression", category: "Creative & Designer" },
  { id: 296, name: "Visual Expression", category: "Creative & Designer" },
  { id: 297, name: "Art Expression", category: "Creative & Designer" },
  { id: 298, name: "Design Master", category: "Creative & Designer" },
  { id: 299, name: "Creative Master", category: "Creative & Designer" },
  { id: 300, name: "Visual Master", category: "Creative & Designer" },

  // 4. Technology & Software (301–400)
  { id: 301, name: "TechCore", category: "Technology & Software" },
  { id: 302, name: "CodeCraft", category: "Technology & Software" },
  { id: 303, name: "DevMatrix", category: "Technology & Software" },
  { id: 304, name: "Software Edge", category: "Technology & Software" },
  { id: 305, name: "TechFlow", category: "Technology & Software" },
  { id: 306, name: "CodeFlow", category: "Technology & Software" },
  { id: 307, name: "DevFlow", category: "Technology & Software" },
  { id: 308, name: "TechGrid", category: "Technology & Software" },
  { id: 309, name: "CodeGrid", category: "Technology & Software" },
  { id: 310, name: "DevGrid", category: "Technology & Software" },
  { id: 311, name: "CloudCore", category: "Technology & Software" },
  { id: 312, name: "CloudEdge", category: "Technology & Software" },
  { id: 313, name: "CloudFlow", category: "Technology & Software" },
  { id: 314, name: "CloudMatrix", category: "Technology & Software" },
  { id: 315, name: "DataCore", category: "Technology & Software" },
  { id: 316, name: "DataEdge", category: "Technology & Software" },
  { id: 317, name: "DataFlow", category: "Technology & Software" },
  { id: 318, name: "DataMatrix", category: "Technology & Software" },
  { id: 319, name: "AI Core", category: "Technology & Software" },
  { id: 320, name: "AI Edge", category: "Technology & Software" },
  { id: 321, name: "AI Flow", category: "Technology & Software" },
  { id: 322, name: "AI Matrix", category: "Technology & Software" },
  { id: 323, name: "CyberCore", category: "Technology & Software" },
  { id: 324, name: "CyberEdge", category: "Technology & Software" },
  { id: 325, name: "CyberFlow", category: "Technology & Software" },
  { id: 326, name: "CyberMatrix", category: "Technology & Software" },
  { id: 327, name: "DevOps Core", category: "Technology & Software" },
  { id: 328, name: "DevOps Edge", category: "Technology & Software" },
  { id: 329, name: "DevOps Flow", category: "Technology & Software" },
  { id: 330, name: "DevOps Matrix", category: "Technology & Software" },
  { id: 331, name: "FullStack Pro", category: "Technology & Software" },
  { id: 332, name: "FullStack Edge", category: "Technology & Software" },
  { id: 333, name: "FullStack Flow", category: "Technology & Software" },
  { id: 334, name: "FullStack Matrix", category: "Technology & Software" },
  { id: 335, name: "Software Pro", category: "Technology & Software" },
  { id: 336, name: "Software Matrix", category: "Technology & Software" },
  { id: 337, name: "Software Flow", category: "Technology & Software" },
  { id: 338, name: "Software Core", category: "Technology & Software" },
  { id: 339, name: "Developer Pro", category: "Technology & Software" },
  { id: 340, name: "Developer Edge", category: "Technology & Software" },
  { id: 341, name: "Developer Flow", category: "Technology & Software" },
  { id: 342, name: "Developer Matrix", category: "Technology & Software" },
  { id: 343, name: "Engineer Core", category: "Technology & Software" },
  { id: 344, name: "Engineer Edge", category: "Technology & Software" },
  { id: 345, name: "Engineer Flow", category: "Technology & Software" },
  { id: 346, name: "Engineer Matrix", category: "Technology & Software" },
  { id: 347, name: "TechVision", category: "Technology & Software" },
  { id: 348, name: "TechPulse", category: "Technology & Software" },
  { id: 349, name: "TechOrbit", category: "Technology & Software" },
  { id: 350, name: "TechHorizon", category: "Technology & Software" },
  { id: 351, name: "CodeVision", category: "Technology & Software" },
  { id: 352, name: "CodePulse", category: "Technology & Software" },
  { id: 353, name: "CodeOrbit", category: "Technology & Software" },
  { id: 354, name: "CodeHorizon", category: "Technology & Software" },
  { id: 355, name: "DevVision", category: "Technology & Software" },
  { id: 356, name: "DevPulse", category: "Technology & Software" },
  { id: 357, name: "DevOrbit", category: "Technology & Software" },
  { id: 358, name: "DevHorizon", category: "Technology & Software" },
  { id: 359, name: "CloudVision", category: "Technology & Software" },
  { id: 360, name: "CloudPulse", category: "Technology & Software" },
  { id: 361, name: "CloudOrbit", category: "Technology & Software" },
  { id: 362, name: "CloudHorizon", category: "Technology & Software" },
  { id: 363, name: "DataVision", category: "Technology & Software" },
  { id: 364, name: "DataPulse", category: "Technology & Software" },
  { id: 365, name: "DataOrbit", category: "Technology & Software" },
  { id: 366, name: "DataHorizon", category: "Technology & Software" },
  { id: 367, name: "AI Vision", category: "Technology & Software" },
  { id: 368, name: "AI Pulse", category: "Technology & Software" },
  { id: 369, name: "AI Orbit", category: "Technology & Software" },
  { id: 370, name: "AI Horizon", category: "Technology & Software" },
  { id: 371, name: "CyberVision", category: "Technology & Software" },
  { id: 372, name: "CyberPulse", category: "Technology & Software" },
  { id: 373, name: "CyberOrbit", category: "Technology & Software" },
  { id: 374, name: "CyberHorizon", category: "Technology & Software" },
  { id: 375, name: "TechBlueprint", category: "Technology & Software" },
  { id: 376, name: "CodeBlueprint", category: "Technology & Software" },
  { id: 377, name: "DevBlueprint", category: "Technology & Software" },
  { id: 378, name: "CloudBlueprint", category: "Technology & Software" },
  { id: 379, name: "DataBlueprint", category: "Technology & Software" },
  { id: 380, name: "AIBlueprint", category: "Technology & Software" },
  { id: 381, name: "CyberBlueprint", category: "Technology & Software" },
  { id: 382, name: "TechStack", category: "Technology & Software" },
  { id: 383, name: "CodeStack", category: "Technology & Software" },
  { id: 384, name: "DevStack", category: "Technology & Software" },
  { id: 385, name: "CloudStack", category: "Technology & Software" },
  { id: 386, name: "DataStack", category: "Technology & Software" },
  { id: 387, name: "AIStack", category: "Technology & Software" },
  { id: 388, name: "CyberStack", category: "Technology & Software" },
  { id: 389, name: "TechLaunch", category: "Technology & Software" },
  { id: 390, name: "CodeLaunch", category: "Technology & Software" },
  { id: 391, name: "DevLaunch", category: "Technology & Software" },
  { id: 392, name: "CloudLaunch", category: "Technology & Software" },
  { id: 393, name: "DataLaunch", category: "Technology & Software" },
  { id: 394, name: "AILaunch", category: "Technology & Software" },
  { id: 395, name: "CyberLaunch", category: "Technology & Software" },
  { id: 396, name: "TechMaster", category: "Technology & Software" },
  { id: 397, name: "CodeMaster", category: "Technology & Software" },
  { id: 398, name: "DevMaster", category: "Technology & Software" },
  { id: 399, name: "CloudMaster", category: "Technology & Software" },
  { id: 400, name: "AI Master", category: "Technology & Software" },

  // 5. Student & Fresher (401–500)
  { id: 401, name: "FreshStart", category: "Student & Fresher" },
  { id: 402, name: "FirstStep", category: "Student & Fresher" },
  { id: 403, name: "Campus Pro", category: "Student & Fresher" },
  { id: 404, name: "Student Edge", category: "Student & Fresher" },
  { id: 405, name: "Graduate Path", category: "Student & Fresher" },
  { id: 406, name: "Graduate Pro", category: "Student & Fresher" },
  { id: 407, name: "Career Starter", category: "Student & Fresher" },
  { id: 408, name: "Career Launchpad", category: "Student & Fresher" },
  { id: 409, name: "First Career", category: "Student & Fresher" },
  { id: 410, name: "NewGen Resume", category: "Student & Fresher" },
  { id: 411, name: "Rising Talent", category: "Student & Fresher" },
  { id: 412, name: "Young Professional", category: "Student & Fresher" },
  { id: 413, name: "Future Pro", category: "Student & Fresher" },
  { id: 414, name: "NextStep", category: "Student & Fresher" },
  { id: 415, name: "NextGen Career", category: "Student & Fresher" },
  { id: 416, name: "Campus Edge", category: "Student & Fresher" },
  { id: 417, name: "Campus Flow", category: "Student & Fresher" },
  { id: 418, name: "Campus Grid", category: "Student & Fresher" },
  { id: 419, name: "Student Flow", category: "Student & Fresher" },
  { id: 420, name: "Student Grid", category: "Student & Fresher" },
  { id: 421, name: "Student Matrix", category: "Student & Fresher" },
  { id: 422, name: "Student Profile", category: "Student & Fresher" },
  { id: 423, name: "Graduate Edge", category: "Student & Fresher" },
  { id: 424, name: "Graduate Flow", category: "Student & Fresher" },
  { id: 425, name: "Graduate Grid", category: "Student & Fresher" },
  { id: 426, name: "Graduate Matrix", category: "Student & Fresher" },
  { id: 427, name: "Fresher Pro", category: "Student & Fresher" },
  { id: 428, name: "Fresher Edge", category: "Student & Fresher" },
  { id: 429, name: "Fresher Flow", category: "Student & Fresher" },
  { id: 430, name: "Fresher Grid", category: "Student & Fresher" },
  { id: 431, name: "Fresher Matrix", category: "Student & Fresher" },
  { id: 432, name: "First Job", category: "Student & Fresher" },
  { id: 433, name: "First Role", category: "Student & Fresher" },
  { id: 434, name: "First Career Pro", category: "Student & Fresher" },
  { id: 435, name: "Career Beginner", category: "Student & Fresher" },
  { id: 436, name: "Career Starter Pro", category: "Student & Fresher" },
  { id: 437, name: "Talent Launch", category: "Student & Fresher" },
  { id: 438, name: "Talent Rise", category: "Student & Fresher" },
  { id: 439, name: "Talent Edge", category: "Student & Fresher" },
  { id: 440, name: "Talent Flow", category: "Student & Fresher" },
  { id: 441, name: "Talent Grid", category: "Student & Fresher" },
  { id: 442, name: "Talent Matrix", category: "Student & Fresher" },
  { id: 443, name: "Young Talent", category: "Student & Fresher" },
  { id: 444, name: "Future Talent", category: "Student & Fresher" },
  { id: 445, name: "Future Career", category: "Student & Fresher" },
  { id: 446, name: "Future Edge", category: "Student & Fresher" },
  { id: 447, name: "Future Flow", category: "Student & Fresher" },
  { id: 448, name: "Future Grid", category: "Student & Fresher" },
  { id: 449, name: "Future Matrix", category: "Student & Fresher" },
  { id: 450, name: "Next Career", category: "Student & Fresher" },
  { id: 451, name: "Next Talent", category: "Student & Fresher" },
  { id: 452, name: "Next Professional", category: "Student & Fresher" },
  { id: 453, name: "Next Graduate", category: "Student & Fresher" },
  { id: 454, name: "Campus Launch", category: "Student & Fresher" },
  { id: 455, name: "Campus Career", category: "Student & Fresher" },
  { id: 456, name: "Campus Talent", category: "Student & Fresher" },
  { id: 457, name: "Campus Vision", category: "Student & Fresher" },
  { id: 458, name: "Student Vision", category: "Student & Fresher" },
  { id: 459, name: "Graduate Vision", category: "Student & Fresher" },
  { id: 460, name: "Fresher Vision", category: "Student & Fresher" },
  { id: 461, name: "Career Vision Fresh", category: "Student & Fresher" },
  { id: 462, name: "Career Rise Fresh", category: "Student & Fresher" },
  { id: 463, name: "Career Spark Fresh", category: "Student & Fresher" },
  { id: 464, name: "Career Pulse Fresh", category: "Student & Fresher" },
  { id: 465, name: "Career Drive Fresh", category: "Student & Fresher" },
  { id: 466, name: "Talent Spark", category: "Student & Fresher" },
  { id: 467, name: "Talent Pulse", category: "Student & Fresher" },
  { id: 468, name: "Talent Drive", category: "Student & Fresher" },
  { id: 469, name: "Talent Orbit", category: "Student & Fresher" },
  { id: 470, name: "Talent Horizon", category: "Student & Fresher" },
  { id: 471, name: "Future Spark", category: "Student & Fresher" },
  { id: 472, name: "Future Pulse", category: "Student & Fresher" },
  { id: 473, name: "Future Drive", category: "Student & Fresher" },
  { id: 474, name: "Future Orbit", category: "Student & Fresher" },
  { id: 475, name: "Future Horizon", category: "Student & Fresher" },
  { id: 476, name: "Graduate Spark", category: "Student & Fresher" },
  { id: 477, name: "Graduate Pulse", category: "Student & Fresher" },
  { id: 478, name: "Graduate Drive", category: "Student & Fresher" },
  { id: 479, name: "Graduate Orbit", category: "Student & Fresher" },
  { id: 480, name: "Graduate Horizon", category: "Student & Fresher" },
  { id: 481, name: "Campus Spark", category: "Student & Fresher" },
  { id: 482, name: "Campus Pulse", category: "Student & Fresher" },
  { id: 483, name: "Campus Drive", category: "Student & Fresher" },
  { id: 484, name: "Campus Orbit", category: "Student & Fresher" },
  { id: 485, name: "Campus Horizon", category: "Student & Fresher" },
  { id: 486, name: "Student Spark", category: "Student & Fresher" },
  { id: 487, name: "Student Pulse", category: "Student & Fresher" },
  { id: 488, name: "Student Drive", category: "Student & Fresher" },
  { id: 489, name: "Student Orbit", category: "Student & Fresher" },
  { id: 490, name: "Student Horizon", category: "Student & Fresher" },
  { id: 491, name: "First Spark", category: "Student & Fresher" },
  { id: 492, name: "First Pulse", category: "Student & Fresher" },
  { id: 493, name: "First Drive", category: "Student & Fresher" },
  { id: 494, name: "First Orbit", category: "Student & Fresher" },
  { id: 495, name: "First Horizon", category: "Student & Fresher" },
  { id: 496, name: "Fresh Spark", category: "Student & Fresher" },
  { id: 497, name: "Fresh Pulse", category: "Student & Fresher" },
  { id: 498, name: "Fresh Drive", category: "Student & Fresher" },
  { id: 499, name: "Fresh Orbit", category: "Student & Fresher" },
  { id: 500, name: "Fresh Horizon", category: "Student & Fresher" },

  // 6. Executive & Leadership (501–600)
  { id: 501, name: "Executive Elite", category: "Executive & Leadership" },
  { id: 502, name: "Executive Prime", category: "Executive & Leadership" },
  { id: 503, name: "Executive Vision", category: "Executive & Leadership" },
  { id: 504, name: "Executive Legacy", category: "Executive & Leadership" },
  { id: 505, name: "Executive Authority", category: "Executive & Leadership" },
  { id: 506, name: "Executive Signature", category: "Executive & Leadership" },
  { id: 507, name: "Executive Prestige", category: "Executive & Leadership" },
  { id: 508, name: "Executive Summit", category: "Executive & Leadership" },
  { id: 509, name: "Executive Crown", category: "Executive & Leadership" },
  { id: 510, name: "Executive Master", category: "Executive & Leadership" },
  { id: 511, name: "Leadership Pro", category: "Executive & Leadership" },
  { id: 512, name: "Leadership Elite", category: "Executive & Leadership" },
  { id: 513, name: "Leadership Prime", category: "Executive & Leadership" },
  { id: 514, name: "Leadership Vision", category: "Executive & Leadership" },
  { id: 515, name: "Leadership Legacy", category: "Executive & Leadership" },
  { id: 516, name: "Leadership Authority", category: "Executive & Leadership" },
  { id: 517, name: "Leadership Signature", category: "Executive & Leadership" },
  { id: 518, name: "Leadership Prestige", category: "Executive & Leadership" },
  { id: 519, name: "Leadership Summit", category: "Executive & Leadership" },
  { id: 520, name: "Leadership Crown", category: "Executive & Leadership" },
  { id: 521, name: "CEO Profile", category: "Executive & Leadership" },
  { id: 522, name: "CEO Elite", category: "Executive & Leadership" },
  { id: 523, name: "CEO Prime", category: "Executive & Leadership" },
  { id: 524, name: "CEO Vision", category: "Executive & Leadership" },
  { id: 525, name: "CEO Legacy", category: "Executive & Leadership" },
  { id: 526, name: "CEO Authority", category: "Executive & Leadership" },
  { id: 527, name: "CEO Signature", category: "Executive & Leadership" },
  { id: 528, name: "CEO Prestige", category: "Executive & Leadership" },
  { id: 529, name: "CEO Summit", category: "Executive & Leadership" },
  { id: 530, name: "CEO Crown", category: "Executive & Leadership" },
  { id: 531, name: "Director Pro", category: "Executive & Leadership" },
  { id: 532, name: "Director Elite", category: "Executive & Leadership" },
  { id: 533, name: "Director Prime", category: "Executive & Leadership" },
  { id: 534, name: "Director Vision", category: "Executive & Leadership" },
  { id: 535, name: "Director Legacy", category: "Executive & Leadership" },
  { id: 536, name: "Director Authority", category: "Executive & Leadership" },
  { id: 537, name: "Director Signature", category: "Executive & Leadership" },
  { id: 538, name: "Director Prestige", category: "Executive & Leadership" },
  { id: 539, name: "Director Summit", category: "Executive & Leadership" },
  { id: 540, name: "Director Crown", category: "Executive & Leadership" },
  { id: 541, name: "Manager Pro", category: "Executive & Leadership" },
  { id: 542, name: "Manager Elite", category: "Executive & Leadership" },
  { id: 543, name: "Manager Prime", category: "Executive & Leadership" },
  { id: 544, name: "Manager Vision", category: "Executive & Leadership" },
  { id: 545, name: "Manager Legacy", category: "Executive & Leadership" },
  { id: 546, name: "Manager Authority", category: "Executive & Leadership" },
  { id: 547, name: "Manager Signature", category: "Executive & Leadership" },
  { id: 548, name: "Manager Prestige", category: "Executive & Leadership" },
  { id: 549, name: "Manager Summit", category: "Executive & Leadership" },
  { id: 550, name: "Manager Crown", category: "Executive & Leadership" },
  { id: 551, name: "Strategy Pro", category: "Executive & Leadership" },
  { id: 552, name: "Strategy Elite", category: "Executive & Leadership" },
  { id: 553, name: "Strategy Prime", category: "Executive & Leadership" },
  { id: 554, name: "Strategy Vision", category: "Executive & Leadership" },
  { id: 555, name: "Strategy Legacy", category: "Executive & Leadership" },
  { id: 556, name: "Strategy Authority", category: "Executive & Leadership" },
  { id: 557, name: "Strategy Signature", category: "Executive & Leadership" },
  { id: 558, name: "Strategy Prestige", category: "Executive & Leadership" },
  { id: 559, name: "Strategy Summit", category: "Executive & Leadership" },
  { id: 560, name: "Strategy Crown", category: "Executive & Leadership" },
  { id: 561, name: "Business Elite", category: "Executive & Leadership" },
  { id: 562, name: "Business Prime", category: "Executive & Leadership" },
  { id: 563, name: "Business Vision", category: "Executive & Leadership" },
  { id: 564, name: "Business Legacy", category: "Executive & Leadership" },
  { id: 565, name: "Business Authority", category: "Executive & Leadership" },
  { id: 566, name: "Business Signature", category: "Executive & Leadership" },
  { id: 567, name: "Business Prestige", category: "Executive & Leadership" },
  { id: 568, name: "Business Summit", category: "Executive & Leadership" },
  { id: 569, name: "Business Crown", category: "Executive & Leadership" },
  { id: 570, name: "Business Master", category: "Executive & Leadership" },
  { id: 571, name: "Corporate Elite", category: "Executive & Leadership" },
  { id: 572, name: "Corporate Prime", category: "Executive & Leadership" },
  { id: 573, name: "Corporate Vision", category: "Executive & Leadership" },
  { id: 574, name: "Corporate Legacy", category: "Executive & Leadership" },
  { id: 575, name: "Corporate Authority", category: "Executive & Leadership" },
  { id: 576, name: "Corporate Signature", category: "Executive & Leadership" },
  { id: 577, name: "Corporate Prestige", category: "Executive & Leadership" },
  { id: 578, name: "Corporate Summit", category: "Executive & Leadership" },
  { id: 579, name: "Corporate Crown", category: "Executive & Leadership" },
  { id: 580, name: "Corporate Master", category: "Executive & Leadership" },
  { id: 581, name: "Leadership Matrix", category: "Executive & Leadership" },
  { id: 582, name: "Leadership Blueprint", category: "Executive & Leadership" },
  { id: 583, name: "Leadership Horizon", category: "Executive & Leadership" },
  { id: 584, name: "Leadership Orbit", category: "Executive & Leadership" },
  { id: 585, name: "Leadership Axis", category: "Executive & Leadership" },
  { id: 586, name: "Executive Matrix", category: "Executive & Leadership" },
  { id: 587, name: "Executive Blueprint", category: "Executive & Leadership" },
  { id: 588, name: "Executive Horizon", category: "Executive & Leadership" },
  { id: 589, name: "Executive Orbit", category: "Executive & Leadership" },
  { id: 590, name: "Executive Axis", category: "Executive & Leadership" },
  { id: 591, name: "CEO Matrix", category: "Executive & Leadership" },
  { id: 592, name: "CEO Blueprint", category: "Executive & Leadership" },
  { id: 593, name: "CEO Horizon", category: "Executive & Leadership" },
  { id: 594, name: "CEO Orbit", category: "Executive & Leadership" },
  { id: 595, name: "CEO Axis", category: "Executive & Leadership" },
  { id: 596, name: "Director Matrix", category: "Executive & Leadership" },
  { id: 597, name: "Director Blueprint", category: "Executive & Leadership" },
  { id: 598, name: "Director Horizon", category: "Executive & Leadership" },
  { id: 599, name: "Director Orbit", category: "Executive & Leadership" },
  { id: 600, name: "Director Axis", category: "Executive & Leadership" },

  // 7. ATS-Friendly (601–700)
  { id: 601, name: "ATS Clear", category: "ATS-Friendly" },
  { id: 602, name: "ATS Prime", category: "ATS-Friendly" },
  { id: 603, name: "ATS Pro", category: "ATS-Friendly" },
  { id: 604, name: "ATS Edge", category: "ATS-Friendly" },
  { id: 605, name: "ATS Focus", category: "ATS-Friendly" },
  { id: 606, name: "ATS Core", category: "ATS-Friendly" },
  { id: 607, name: "ATS Grid", category: "ATS-Friendly" },
  { id: 608, name: "ATS Simple", category: "ATS-Friendly" },
  { id: 609, name: "ATS Standard", category: "ATS-Friendly" },
  { id: 610, name: "ATS Professional", category: "ATS-Friendly" },
  { id: 611, name: "ATS Career", category: "ATS-Friendly" },
  { id: 612, name: "ATS Executive", category: "ATS-Friendly" },
  { id: 613, name: "ATS Graduate", category: "ATS-Friendly" },
  { id: 614, name: "ATS Fresh", category: "ATS-Friendly" },
  { id: 615, name: "ATS Tech", category: "ATS-Friendly" },
  { id: 616, name: "ATS Business", category: "ATS-Friendly" },
  { id: 617, name: "ATS Finance", category: "ATS-Friendly" },
  { id: 618, name: "ATS Marketing", category: "ATS-Friendly" },
  { id: 619, name: "ATS Engineering", category: "ATS-Friendly" },
  { id: 620, name: "ATS Developer", category: "ATS-Friendly" },
  { id: 621, name: "ATS Software", category: "ATS-Friendly" },
  { id: 622, name: "ATS Cloud", category: "ATS-Friendly" },
  { id: 623, name: "ATS Data", category: "ATS-Friendly" },
  { id: 624, name: "ATS AI", category: "ATS-Friendly" },
  { id: 625, name: "ATS Cyber", category: "ATS-Friendly" },
  { id: 626, name: "ATS Manager", category: "ATS-Friendly" },
  { id: 627, name: "ATS Leader", category: "ATS-Friendly" },
  { id: 628, name: "ATS Corporate", category: "ATS-Friendly" },
  { id: 629, name: "ATS Global", category: "ATS-Friendly" },
  { id: 630, name: "ATS International", category: "ATS-Friendly" },
  { id: 631, name: "ATS Classic", category: "ATS-Friendly" },
  { id: 632, name: "ATS Modern", category: "ATS-Friendly" },
  { id: 633, name: "ATS Minimal", category: "ATS-Friendly" },
  { id: 634, name: "ATS Clean", category: "ATS-Friendly" },
  { id: 635, name: "ATS White", category: "ATS-Friendly" },
  { id: 636, name: "ATS Mono", category: "ATS-Friendly" },
  { id: 637, name: "ATS Structured", category: "ATS-Friendly" },
  { id: 638, name: "ATS Matrix", category: "ATS-Friendly" },
  { id: 639, name: "ATS Framework", category: "ATS-Friendly" },
  { id: 640, name: "ATS Blueprint", category: "ATS-Friendly" },
  { id: 641, name: "ATS Profile", category: "ATS-Friendly" },
  { id: 642, name: "ATS Career Pro", category: "ATS-Friendly" },
  { id: 643, name: "ATS Career Edge", category: "ATS-Friendly" },
  { id: 644, name: "ATS Career Focus", category: "ATS-Friendly" },
  { id: 645, name: "ATS Career Core", category: "ATS-Friendly" },
  { id: 646, name: "ATS Career Grid", category: "ATS-Friendly" },
  { id: 647, name: "ATS Career Matrix", category: "ATS-Friendly" },
  { id: 648, name: "ATS Career Structure", category: "ATS-Friendly" },
  { id: 649, name: "ATS Career Blueprint", category: "ATS-Friendly" },
  { id: 650, name: "ATS Career Frame", category: "ATS-Friendly" },
  { id: 651, name: "ATS Resume Pro", category: "ATS-Friendly" },
  { id: 652, name: "ATS Resume Edge", category: "ATS-Friendly" },
  { id: 653, name: "ATS Resume Focus", category: "ATS-Friendly" },
  { id: 654, name: "ATS Resume Core", category: "ATS-Friendly" },
  { id: 655, name: "ATS Resume Grid", category: "ATS-Friendly" },
  { id: 656, name: "ATS Resume Matrix", category: "ATS-Friendly" },
  { id: 657, name: "ATS Resume Structure", category: "ATS-Friendly" },
  { id: 658, name: "ATS Resume Blueprint", category: "ATS-Friendly" },
  { id: 659, name: "ATS Resume Frame", category: "ATS-Friendly" },
  { id: 660, name: "ATS Resume Plus", category: "ATS-Friendly" },
  { id: 661, name: "ATS Professional Pro", category: "ATS-Friendly" },
  { id: 662, name: "ATS Professional Edge", category: "ATS-Friendly" },
  { id: 663, name: "ATS Professional Focus", category: "ATS-Friendly" },
  { id: 664, name: "ATS Professional Core", category: "ATS-Friendly" },
  { id: 665, name: "ATS Professional Grid", category: "ATS-Friendly" },
  { id: 666, name: "ATS Professional Matrix", category: "ATS-Friendly" },
  { id: 667, name: "ATS Professional Structure", category: "ATS-Friendly" },
  { id: 668, name: "ATS Professional Blueprint", category: "ATS-Friendly" },
  { id: 669, name: "ATS Professional Frame", category: "ATS-Friendly" },
  { id: 670, name: "ATS Professional Plus", category: "ATS-Friendly" },
  { id: 671, name: "ATS Executive Pro", category: "ATS-Friendly" },
  { id: 672, name: "ATS Executive Edge", category: "ATS-Friendly" },
  { id: 673, name: "ATS Executive Focus", category: "ATS-Friendly" },
  { id: 674, name: "ATS Executive Core", category: "ATS-Friendly" },
  { id: 675, name: "ATS Executive Grid", category: "ATS-Friendly" },
  { id: 676, name: "ATS Executive Matrix", category: "ATS-Friendly" },
  { id: 677, name: "ATS Executive Structure", category: "ATS-Friendly" },
  { id: 678, name: "ATS Executive Blueprint", category: "ATS-Friendly" },
  { id: 679, name: "ATS Executive Frame", category: "ATS-Friendly" },
  { id: 680, name: "ATS Executive Plus", category: "ATS-Friendly" },
  { id: 681, name: "ATS Tech Pro", category: "ATS-Friendly" },
  { id: 682, name: "ATS Tech Edge", category: "ATS-Friendly" },
  { id: 683, name: "ATS Tech Focus", category: "ATS-Friendly" },
  { id: 684, name: "ATS Tech Core", category: "ATS-Friendly" },
  { id: 685, name: "ATS Tech Grid", category: "ATS-Friendly" },
  { id: 686, name: "ATS Tech Matrix", category: "ATS-Friendly" },
  { id: 687, name: "ATS Tech Structure", category: "ATS-Friendly" },
  { id: 688, name: "ATS Tech Blueprint", category: "ATS-Friendly" },
  { id: 689, name: "ATS Tech Frame", category: "ATS-Friendly" },
  { id: 690, name: "ATS Tech Plus", category: "ATS-Friendly" },
  { id: 691, name: "ATS Graduate Pro", category: "ATS-Friendly" },
  { id: 692, name: "ATS Graduate Edge", category: "ATS-Friendly" },
  { id: 693, name: "ATS Graduate Focus", category: "ATS-Friendly" },
  { id: 694, name: "ATS Graduate Core", category: "ATS-Friendly" },
  { id: 695, name: "ATS Graduate Grid", category: "ATS-Friendly" },
  { id: 696, name: "ATS Graduate Matrix", category: "ATS-Friendly" },
  { id: 697, name: "ATS Graduate Structure", category: "ATS-Friendly" },
  { id: 698, name: "ATS Graduate Blueprint", category: "ATS-Friendly" },
  { id: 699, name: "ATS Graduate Frame", category: "ATS-Friendly" },
  { id: 700, name: "ATS Graduate Plus", category: "ATS-Friendly" },

  // 8. Futuristic / AI / Digital (701–800)
  { id: 701, name: "Neural Profile", category: "Futuristic / AI / Digital" },
  { id: 702, name: "Quantum Resume", category: "Futuristic / AI / Digital" },
  { id: 703, name: "Cyber Future", category: "Futuristic / AI / Digital" },
  { id: 704, name: "AI Nexus", category: "Futuristic / AI / Digital" },
  { id: 705, name: "Digital Pulse", category: "Futuristic / AI / Digital" },
  { id: 706, name: "Neural Flow", category: "Futuristic / AI / Digital" },
  { id: 707, name: "Quantum Grid", category: "Futuristic / AI / Digital" },
  { id: 708, name: "Future Matrix", category: "Futuristic / AI / Digital" },
  { id: 709, name: "Digital Core", category: "Futuristic / AI / Digital" },
  { id: 710, name: "Neural Edge", category: "Futuristic / AI / Digital" },
  { id: 711, name: "AI Horizon", category: "Futuristic / AI / Digital" },
  { id: 712, name: "Quantum Horizon", category: "Futuristic / AI / Digital" },
  { id: 713, name: "Cyber Horizon", category: "Futuristic / AI / Digital" },
  { id: 714, name: "Digital Horizon", category: "Futuristic / AI / Digital" },
  { id: 715, name: "Neural Horizon", category: "Futuristic / AI / Digital" },
  { id: 716, name: "AI Orbit", category: "Futuristic / AI / Digital" },
  { id: 717, name: "Quantum Orbit", category: "Futuristic / AI / Digital" },
  { id: 718, name: "Cyber Orbit", category: "Futuristic / AI / Digital" },
  { id: 719, name: "Digital Orbit", category: "Futuristic / AI / Digital" },
  { id: 720, name: "Neural Orbit", category: "Futuristic / AI / Digital" },
  { id: 721, name: "AI Matrix", category: "Futuristic / AI / Digital" },
  { id: 722, name: "Quantum Matrix", category: "Futuristic / AI / Digital" },
  { id: 723, name: "Cyber Matrix", category: "Futuristic / AI / Digital" },
  { id: 724, name: "Digital Matrix", category: "Futuristic / AI / Digital" },
  { id: 725, name: "Neural Matrix", category: "Futuristic / AI / Digital" },
  { id: 726, name: "AI Blueprint", category: "Futuristic / AI / Digital" },
  { id: 727, name: "Quantum Blueprint", category: "Futuristic / AI / Digital" },
  { id: 728, name: "Cyber Blueprint", category: "Futuristic / AI / Digital" },
  { id: 729, name: "Digital Blueprint", category: "Futuristic / AI / Digital" },
  { id: 730, name: "Neural Blueprint", category: "Futuristic / AI / Digital" },
  { id: 731, name: "AI Circuit", category: "Futuristic / AI / Digital" },
  { id: 732, name: "Quantum Circuit", category: "Futuristic / AI / Digital" },
  { id: 733, name: "Cyber Circuit", category: "Futuristic / AI / Digital" },
  { id: 734, name: "Digital Circuit", category: "Futuristic / AI / Digital" },
  { id: 735, name: "Neural Circuit", category: "Futuristic / AI / Digital" },
  { id: 736, name: "AI Network", category: "Futuristic / AI / Digital" },
  { id: 737, name: "Quantum Network", category: "Futuristic / AI / Digital" },
  { id: 738, name: "Cyber Network", category: "Futuristic / AI / Digital" },
  { id: 739, name: "Digital Network", category: "Futuristic / AI / Digital" },
  { id: 740, name: "Neural Network", category: "Futuristic / AI / Digital" },
  { id: 741, name: "AI Vector", category: "Futuristic / AI / Digital" },
  { id: 742, name: "Quantum Vector", category: "Futuristic / AI / Digital" },
  { id: 743, name: "Cyber Vector", category: "Futuristic / AI / Digital" },
  { id: 744, name: "Digital Vector", category: "Futuristic / AI / Digital" },
  { id: 745, name: "Neural Vector", category: "Futuristic / AI / Digital" },
  { id: 746, name: "AI Signal", category: "Futuristic / AI / Digital" },
  { id: 747, name: "Quantum Signal", category: "Futuristic / AI / Digital" },
  { id: 748, name: "Cyber Signal", category: "Futuristic / AI / Digital" },
  { id: 749, name: "Digital Signal", category: "Futuristic / AI / Digital" },
  { id: 750, name: "Neural Signal", category: "Futuristic / AI / Digital" },
  { id: 751, name: "AI Interface", category: "Futuristic / AI / Digital" },
  { id: 752, name: "Quantum Interface", category: "Futuristic / AI / Digital" },
  { id: 753, name: "Cyber Interface", category: "Futuristic / AI / Digital" },
  { id: 754, name: "Digital Interface", category: "Futuristic / AI / Digital" },
  { id: 755, name: "Neural Interface", category: "Futuristic / AI / Digital" },
  { id: 756, name: "AI Framework", category: "Futuristic / AI / Digital" },
  { id: 757, name: "Quantum Framework", category: "Futuristic / AI / Digital" },
  { id: 758, name: "Cyber Framework", category: "Futuristic / AI / Digital" },
  { id: 759, name: "Digital Framework", category: "Futuristic / AI / Digital" },
  { id: 760, name: "Neural Framework", category: "Futuristic / AI / Digital" },
  { id: 761, name: "AI Vision", category: "Futuristic / AI / Digital" },
  { id: 762, name: "Quantum Vision", category: "Futuristic / AI / Digital" },
  { id: 763, name: "Cyber Vision", category: "Futuristic / AI / Digital" },
  { id: 764, name: "Digital Vision", category: "Futuristic / AI / Digital" },
  { id: 765, name: "Neural Vision", category: "Futuristic / AI / Digital" },
  { id: 766, name: "AI Future", category: "Futuristic / AI / Digital" },
  { id: 767, name: "Quantum Future", category: "Futuristic / AI / Digital" },
  { id: 768, name: "Cyber Future Pro", category: "Futuristic / AI / Digital" },
  { id: 769, name: "Digital Future", category: "Futuristic / AI / Digital" },
  { id: 770, name: "Neural Future", category: "Futuristic / AI / Digital" },
  { id: 771, name: "AI Evolution", category: "Futuristic / AI / Digital" },
  { id: 772, name: "Quantum Evolution", category: "Futuristic / AI / Digital" },
  { id: 773, name: "Cyber Evolution", category: "Futuristic / AI / Digital" },
  { id: 774, name: "Digital Evolution", category: "Futuristic / AI / Digital" },
  { id: 775, name: "Neural Evolution", category: "Futuristic / AI / Digital" },
  { id: 776, name: "AI Intelligence", category: "Futuristic / AI / Digital" },
  { id: 777, name: "Quantum Intelligence", category: "Futuristic / AI / Digital" },
  { id: 778, name: "Cyber Intelligence", category: "Futuristic / AI / Digital" },
  { id: 779, name: "Digital Intelligence", category: "Futuristic / AI / Digital" },
  { id: 780, name: "Neural Intelligence", category: "Futuristic / AI / Digital" },
  { id: 781, name: "AI Generation", category: "Futuristic / AI / Digital" },
  { id: 782, name: "Quantum Generation", category: "Futuristic / AI / Digital" },
  { id: 783, name: "Cyber Generation", category: "Futuristic / AI / Digital" },
  { id: 784, name: "Digital Generation", category: "Futuristic / AI / Digital" },
  { id: 785, name: "Neural Generation", category: "Futuristic / AI / Digital" },
  { id: 786, name: "AI Revolution", category: "Futuristic / AI / Digital" },
  { id: 787, name: "Quantum Revolution", category: "Futuristic / AI / Digital" },
  { id: 788, name: "Cyber Revolution", category: "Futuristic / AI / Digital" },
  { id: 789, name: "Digital Revolution", category: "Futuristic / AI / Digital" },
  { id: 790, name: "Neural Revolution", category: "Futuristic / AI / Digital" },
  { id: 791, name: "AI Infinity", category: "Futuristic / AI / Digital" },
  { id: 792, name: "Quantum Infinity", category: "Futuristic / AI / Digital" },
  { id: 793, name: "Cyber Infinity", category: "Futuristic / AI / Digital" },
  { id: 794, name: "Digital Infinity", category: "Futuristic / AI / Digital" },
  { id: 795, name: "Neural Infinity", category: "Futuristic / AI / Digital" },
  { id: 796, name: "AI Fusion", category: "Futuristic / AI / Digital" },
  { id: 797, name: "Quantum Fusion", category: "Futuristic / AI / Digital" },
  { id: 798, name: "Cyber Fusion", category: "Futuristic / AI / Digital" },
  { id: 799, name: "Digital Fusion", category: "Futuristic / AI / Digital" },
  { id: 800, name: "Neural Fusion", category: "Futuristic / AI / Digital" },

  // 9. Neomorphism / Liquid Glass / Premium (801–900)
  { id: 801, name: "Neo Profile", category: "Neomorphism / Liquid Glass" },
  { id: 802, name: "Neo Career", category: "Neomorphism / Liquid Glass" },
  { id: 803, name: "Neo Professional", category: "Neomorphism / Liquid Glass" },
  { id: 804, name: "Neo Executive", category: "Neomorphism / Liquid Glass" },
  { id: 805, name: "Neo Minimal", category: "Neomorphism / Liquid Glass" },
  { id: 806, name: "Neo Grid", category: "Neomorphism / Liquid Glass" },
  { id: 807, name: "Neo Matrix", category: "Neomorphism / Liquid Glass" },
  { id: 808, name: "Neo Flow", category: "Neomorphism / Liquid Glass" },
  { id: 809, name: "Neo Edge", category: "Neomorphism / Liquid Glass" },
  { id: 810, name: "Neo Prime", category: "Neomorphism / Liquid Glass" },
  { id: 811, name: "Neo Elite", category: "Neomorphism / Liquid Glass" },
  { id: 812, name: "Neo Vision", category: "Neomorphism / Liquid Glass" },
  { id: 813, name: "Neo Horizon", category: "Neomorphism / Liquid Glass" },
  { id: 814, name: "Neo Orbit", category: "Neomorphism / Liquid Glass" },
  { id: 815, name: "Neo Core", category: "Neomorphism / Liquid Glass" },
  { id: 816, name: "Neo Focus", category: "Neomorphism / Liquid Glass" },
  { id: 817, name: "Neo Frame", category: "Neomorphism / Liquid Glass" },
  { id: 818, name: "Neo Structure", category: "Neomorphism / Liquid Glass" },
  { id: 819, name: "Neo Blueprint", category: "Neomorphism / Liquid Glass" },
  { id: 820, name: "Neo Signature", category: "Neomorphism / Liquid Glass" },
  { id: 821, name: "Liquid Profile", category: "Neomorphism / Liquid Glass" },
  { id: 822, name: "Liquid Career", category: "Neomorphism / Liquid Glass" },
  { id: 823, name: "Liquid Professional", category: "Neomorphism / Liquid Glass" },
  { id: 824, name: "Liquid Executive", category: "Neomorphism / Liquid Glass" },
  { id: 825, name: "Liquid Minimal", category: "Neomorphism / Liquid Glass" },
  { id: 826, name: "Liquid Grid", category: "Neomorphism / Liquid Glass" },
  { id: 827, name: "Liquid Matrix", category: "Neomorphism / Liquid Glass" },
  { id: 828, name: "Liquid Flow", category: "Neomorphism / Liquid Glass" },
  { id: 829, name: "Liquid Edge", category: "Neomorphism / Liquid Glass" },
  { id: 830, name: "Liquid Prime", category: "Neomorphism / Liquid Glass" },
  { id: 831, name: "Liquid Elite", category: "Neomorphism / Liquid Glass" },
  { id: 832, name: "Liquid Vision", category: "Neomorphism / Liquid Glass" },
  { id: 833, name: "Liquid Horizon", category: "Neomorphism / Liquid Glass" },
  { id: 834, name: "Liquid Orbit", category: "Neomorphism / Liquid Glass" },
  { id: 835, name: "Liquid Core", category: "Neomorphism / Liquid Glass" },
  { id: 836, name: "Liquid Focus", category: "Neomorphism / Liquid Glass" },
  { id: 837, name: "Liquid Frame", category: "Neomorphism / Liquid Glass" },
  { id: 838, name: "Liquid Structure", category: "Neomorphism / Liquid Glass" },
  { id: 839, name: "Liquid Blueprint", category: "Neomorphism / Liquid Glass" },
  { id: 840, name: "Liquid Signature", category: "Neomorphism / Liquid Glass" },
  { id: 841, name: "Glass Profile", category: "Neomorphism / Liquid Glass" },
  { id: 842, name: "Glass Career", category: "Neomorphism / Liquid Glass" },
  { id: 843, name: "Glass Professional", category: "Neomorphism / Liquid Glass" },
  { id: 844, name: "Glass Executive", category: "Neomorphism / Liquid Glass" },
  { id: 845, name: "Glass Minimal", category: "Neomorphism / Liquid Glass" },
  { id: 846, name: "Glass Grid", category: "Neomorphism / Liquid Glass" },
  { id: 847, name: "Glass Matrix", category: "Neomorphism / Liquid Glass" },
  { id: 848, name: "Glass Flow", category: "Neomorphism / Liquid Glass" },
  { id: 849, name: "Glass Edge", category: "Neomorphism / Liquid Glass" },
  { id: 850, name: "Glass Prime", category: "Neomorphism / Liquid Glass" },
  { id: 851, name: "Glass Elite", category: "Neomorphism / Liquid Glass" },
  { id: 852, name: "Glass Vision", category: "Neomorphism / Liquid Glass" },
  { id: 853, name: "Glass Horizon", category: "Neomorphism / Liquid Glass" },
  { id: 854, name: "Glass Orbit", category: "Neomorphism / Liquid Glass" },
  { id: 855, name: "Glass Core", category: "Neomorphism / Liquid Glass" },
  { id: 856, name: "Glass Focus", category: "Neomorphism / Liquid Glass" },
  { id: 857, name: "Glass Frame", category: "Neomorphism / Liquid Glass" },
  { id: 858, name: "Glass Structure", category: "Neomorphism / Liquid Glass" },
  { id: 859, name: "Glass Blueprint", category: "Neomorphism / Liquid Glass" },
  { id: 860, name: "Glass Signature", category: "Neomorphism / Liquid Glass" },
  { id: 861, name: "Crystal Profile", category: "Neomorphism / Liquid Glass" },
  { id: 862, name: "Crystal Career", category: "Neomorphism / Liquid Glass" },
  { id: 863, name: "Crystal Professional", category: "Neomorphism / Liquid Glass" },
  { id: 864, name: "Crystal Executive", category: "Neomorphism / Liquid Glass" },
  { id: 865, name: "Crystal Minimal", category: "Neomorphism / Liquid Glass" },
  { id: 866, name: "Crystal Grid", category: "Neomorphism / Liquid Glass" },
  { id: 867, name: "Crystal Matrix", category: "Neomorphism / Liquid Glass" },
  { id: 868, name: "Crystal Flow", category: "Neomorphism / Liquid Glass" },
  { id: 869, name: "Crystal Edge", category: "Neomorphism / Liquid Glass" },
  { id: 870, name: "Crystal Prime", category: "Neomorphism / Liquid Glass" },
  { id: 871, name: "Crystal Elite", category: "Neomorphism / Liquid Glass" },
  { id: 872, name: "Crystal Vision", category: "Neomorphism / Liquid Glass" },
  { id: 873, name: "Crystal Horizon", category: "Neomorphism / Liquid Glass" },
  { id: 874, name: "Crystal Orbit", category: "Neomorphism / Liquid Glass" },
  { id: 875, name: "Crystal Core", category: "Neomorphism / Liquid Glass" },
  { id: 876, name: "Crystal Focus", category: "Neomorphism / Liquid Glass" },
  { id: 877, name: "Crystal Frame", category: "Neomorphism / Liquid Glass" },
  { id: 878, name: "Crystal Structure", category: "Neomorphism / Liquid Glass" },
  { id: 879, name: "Crystal Blueprint", category: "Neomorphism / Liquid Glass" },
  { id: 880, name: "Crystal Signature", category: "Neomorphism / Liquid Glass" },
  { id: 881, name: "Premium Profile", category: "Neomorphism / Liquid Glass" },
  { id: 882, name: "Premium Career", category: "Neomorphism / Liquid Glass" },
  { id: 883, name: "Premium Professional", category: "Neomorphism / Liquid Glass" },
  { id: 884, name: "Premium Executive", category: "Neomorphism / Liquid Glass" },
  { id: 885, name: "Premium Minimal", category: "Neomorphism / Liquid Glass" },
  { id: 886, name: "Premium Grid", category: "Neomorphism / Liquid Glass" },
  { id: 887, name: "Premium Matrix", category: "Neomorphism / Liquid Glass" },
  { id: 888, name: "Premium Flow", category: "Neomorphism / Liquid Glass" },
  { id: 889, name: "Premium Edge", category: "Neomorphism / Liquid Glass" },
  { id: 890, name: "Premium Prime", category: "Neomorphism / Liquid Glass" },
  { id: 891, name: "Premium Elite", category: "Neomorphism / Liquid Glass" },
  { id: 892, name: "Premium Vision", category: "Neomorphism / Liquid Glass" },
  { id: 893, name: "Premium Horizon", category: "Neomorphism / Liquid Glass" },
  { id: 894, name: "Premium Orbit", category: "Neomorphism / Liquid Glass" },
  { id: 895, name: "Premium Core", category: "Neomorphism / Liquid Glass" },
  { id: 896, name: "Premium Focus", category: "Neomorphism / Liquid Glass" },
  { id: 897, name: "Premium Frame", category: "Neomorphism / Liquid Glass" },
  { id: 898, name: "Premium Structure", category: "Neomorphism / Liquid Glass" },
  { id: 899, name: "Premium Blueprint", category: "Neomorphism / Liquid Glass" },
  { id: 900, name: "Premium Signature", category: "Neomorphism / Liquid Glass" },

  // 10. Industry-Specific (901–1,000+)
  { id: 901, name: "Software Engineer Pro", category: "Industry-Specific" },
  { id: 902, name: "Full Stack Engineer", category: "Industry-Specific" },
  { id: 903, name: "Frontend Developer", category: "Industry-Specific" },
  { id: 904, name: "Backend Developer", category: "Industry-Specific" },
  { id: 905, name: "Mobile Developer", category: "Industry-Specific" },
  { id: 906, name: "Android Developer", category: "Industry-Specific" },
  { id: 907, name: "iOS Developer", category: "Industry-Specific" },
  { id: 908, name: "Web Developer", category: "Industry-Specific" },
  { id: 909, name: "Cloud Engineer", category: "Industry-Specific" },
  { id: 910, name: "AWS Engineer", category: "Industry-Specific" },
  { id: 911, name: "Azure Engineer", category: "Industry-Specific" },
  { id: 912, name: "DevOps Engineer", category: "Industry-Specific" },
  { id: 913, name: "Data Engineer", category: "Industry-Specific" },
  { id: 914, name: "Data Scientist", category: "Industry-Specific" },
  { id: 915, name: "Machine Learning Engineer", category: "Industry-Specific" },
  { id: 916, name: "AI Engineer", category: "Industry-Specific" },
  { id: 917, name: "Cybersecurity Analyst", category: "Industry-Specific" },
  { id: 918, name: "Security Engineer", category: "Industry-Specific" },
  { id: 919, name: "Network Engineer", category: "Industry-Specific" },
  { id: 920, name: "Database Administrator", category: "Industry-Specific" },
  { id: 921, name: "UI UX Designer", category: "Industry-Specific" },
  { id: 922, name: "Product Designer", category: "Industry-Specific" },
  { id: 923, name: "Graphic Designer", category: "Industry-Specific" },
  { id: 924, name: "Motion Designer", category: "Industry-Specific" },
  { id: 925, name: "Creative Director", category: "Industry-Specific" },
  { id: 926, name: "Product Manager", category: "Industry-Specific" },
  { id: 927, name: "Project Manager", category: "Industry-Specific" },
  { id: 928, name: "Business Analyst", category: "Industry-Specific" },
  { id: 929, name: "Data Analyst", category: "Industry-Specific" },
  { id: 930, name: "Financial Analyst", category: "Industry-Specific" },
  { id: 931, name: "Investment Analyst", category: "Industry-Specific" },
  { id: 932, name: "Marketing Manager", category: "Industry-Specific" },
  { id: 933, name: "Digital Marketer", category: "Industry-Specific" },
  { id: 934, name: "SEO Specialist", category: "Industry-Specific" },
  { id: 935, name: "Content Strategist", category: "Industry-Specific" },
  { id: 936, name: "Social Media Manager", category: "Industry-Specific" },
  { id: 937, name: "Brand Manager", category: "Industry-Specific" },
  { id: 938, name: "Sales Executive", category: "Industry-Specific" },
  { id: 939, name: "Sales Manager", category: "Industry-Specific" },
  { id: 940, name: "HR Executive", category: "Industry-Specific" },
  { id: 941, name: "HR Manager", category: "Industry-Specific" },
  { id: 942, name: "Recruiter Pro", category: "Industry-Specific" },
  { id: 943, name: "Operations Manager", category: "Industry-Specific" },
  { id: 944, name: "Operations Executive", category: "Industry-Specific" },
  { id: 945, name: "Management Consultant", category: "Industry-Specific" },
  { id: 946, name: "Strategy Consultant", category: "Industry-Specific" },
  { id: 947, name: "Entrepreneur Pro", category: "Industry-Specific" },
  { id: 948, name: "Startup Founder", category: "Industry-Specific" },
  { id: 949, name: "Business Development", category: "Industry-Specific" },
  { id: 950, name: "Customer Success", category: "Industry-Specific" },
  { id: 951, name: "Accountant Pro", category: "Industry-Specific" },
  { id: 952, name: "Auditor Pro", category: "Industry-Specific" },
  { id: 953, name: "Banking Professional", category: "Industry-Specific" },
  { id: 954, name: "Finance Executive", category: "Industry-Specific" },
  { id: 955, name: "Investment Banking", category: "Industry-Specific" },
  { id: 956, name: "Doctor Professional", category: "Industry-Specific" },
  { id: 957, name: "Medical Student", category: "Industry-Specific" },
  { id: 958, name: "Healthcare Professional", category: "Industry-Specific" },
  { id: 959, name: "Pharmacist Pro", category: "Industry-Specific" },
  { id: 960, name: "Nursing Professional", category: "Industry-Specific" },
  { id: 961, name: "Biotechnology Pro", category: "Industry-Specific" },
  { id: 962, name: "Research Scientist", category: "Industry-Specific" },
  { id: 963, name: "Mechanical Engineer", category: "Industry-Specific" },
  { id: 964, name: "Civil Engineer", category: "Industry-Specific" },
  { id: 965, name: "Electrical Engineer", category: "Industry-Specific" },
  { id: 966, name: "Electronics Engineer", category: "Industry-Specific" },
  { id: 967, name: "Chemical Engineer", category: "Industry-Specific" },
  { id: 968, name: "Automobile Engineer", category: "Industry-Specific" },
  { id: 969, name: "Aerospace Engineer", category: "Industry-Specific" },
  { id: 970, name: "Robotics Engineer", category: "Industry-Specific" },
  { id: 971, name: "IoT Engineer", category: "Industry-Specific" },
  { id: 972, name: "Embedded Engineer", category: "Industry-Specific" },
  { id: 973, name: "VLSI Engineer", category: "Industry-Specific" },
  { id: 974, name: "Telecom Engineer", category: "Industry-Specific" },
  { id: 975, name: "Architect Pro", category: "Industry-Specific" },
  { id: 976, name: "Interior Designer", category: "Industry-Specific" },
  { id: 977, name: "Fashion Designer", category: "Industry-Specific" },
  { id: 978, name: "Teacher Pro", category: "Industry-Specific" },
  { id: 979, name: "Professor Pro", category: "Industry-Specific" },
  { id: 980, name: "Academic Researcher", category: "Industry-Specific" },
  { id: 981, name: "Lawyer Professional", category: "Industry-Specific" },
  { id: 982, name: "Legal Consultant", category: "Industry-Specific" },
  { id: 983, name: "Journalist Pro", category: "Industry-Specific" },
  { id: 984, name: "Photographer Pro", category: "Industry-Specific" },
  { id: 985, name: "Filmmaker Pro", category: "Industry-Specific" },
  { id: 986, name: "Video Editor", category: "Industry-Specific" },
  { id: 987, name: "Animator Pro", category: "Industry-Specific" },
  { id: 988, name: "Game Developer", category: "Industry-Specific" },
  { id: 989, name: "Game Designer", category: "Industry-Specific" },
  { id: 990, name: "Product Photographer", category: "Industry-Specific" },
  { id: 991, name: "Event Manager", category: "Industry-Specific" },
  { id: 992, name: "Hospitality Professional", category: "Industry-Specific" },
  { id: 993, name: "Travel Professional", category: "Industry-Specific" },
  { id: 994, name: "Aviation Professional", category: "Industry-Specific" },
  { id: 995, name: "Government Professional", category: "Industry-Specific" },
  { id: 996, name: "Public Administration", category: "Industry-Specific" },
  { id: 997, name: "NGO Professional", category: "Industry-Specific" },
  { id: 998, name: "Social Impact", category: "Industry-Specific" },
  { id: 999, name: "Research Professional", category: "Industry-Specific" },
  { id: 1000, name: "Global Professional", category: "Industry-Specific" },
  { id: 1001, name: "International Career", category: "Industry-Specific" },
  { id: 1002, name: "Global Executive", category: "Industry-Specific" },
  { id: 1003, name: "Global Tech", category: "Industry-Specific" },
  { id: 1004, name: "Global Graduate", category: "Industry-Specific" },
  { id: 1005, name: "Global ATS", category: "Industry-Specific" },
  { id: 1006, name: "Global Minimal", category: "Industry-Specific" },
  { id: 1007, name: "Global Creative", category: "Industry-Specific" },
  { id: 1008, name: "Global Premium", category: "Industry-Specific" },
  { id: 1009, name: "Global Future", category: "Industry-Specific" },
  { id: 1010, name: "Global Elite", category: "Industry-Specific" }
];

export const TEMPLATES_LIBRARY: TemplateItem[] = templateRawData.map(item => {
  const meta = categoryStyleMap[item.category] || { baseStyle: "modern", defaultAccent: "#d97706" };
  let specificStyle = meta.baseStyle;

  // Custom fine-tuning of base styles based on template name keywords
  const lname = item.name.toLowerCase();
  if (lname.includes("photo") || lname.includes("profile photo")) specificStyle = "profile-photo";
  else if (lname.includes("serif") || lname.includes("academic") || lname.includes("editorial")) specificStyle = "academic";
  else if (lname.includes("classic") || lname.includes("ats")) specificStyle = "classic";
  else if (lname.includes("executive") || lname.includes("ceo") || lname.includes("director")) specificStyle = "executive";
  else if (lname.includes("minimal") || lname.includes("chic") || lname.includes("mono")) specificStyle = "chic";
  else if (lname.includes("brutalist")) specificStyle = "brutalist";
  else if (lname.includes("slate")) specificStyle = "slate";
  else if (lname.includes("healthcare") || lname.includes("doctor") || lname.includes("medical") || lname.includes("nurse")) specificStyle = "healthcare";
  else if (lname.includes("future") || lname.includes("ai ") || lname.includes("quantum") || lname.includes("cyber") || lname.includes("neural")) specificStyle = "future";
  else if (lname.includes("neo") || lname.includes("glass") || lname.includes("liquid") || lname.includes("midnight")) specificStyle = "midnight";

  return {
    id: item.id,
    name: item.name,
    category: item.category,
    baseStyle: specificStyle,
    colorAccent: meta.defaultAccent,
    badge: `#${item.id}`,
    description: `Professional template design customized for ${item.category} (${item.name}).`
  };
});

export const getTemplateById = (id: number): TemplateItem | undefined => {
  return TEMPLATES_LIBRARY.find(t => t.id === id);
};
